apiVersion: apps/v1
kind: Deployment
metadata:
   label:
      app.kubernetes.io/name: serviceAccount1
   name: serviceAccount1
   namespace: kube-system
spec:
   selector:
      matchLables:
         app.kubernetes.io/name: serviceAccount1
   template: 
      metadata:
        label:
           app.kubernetes.io/name: serviceAccount1
      spec:
        containers:
        -name: serviceAccount1
         args: 
         image: docker.io/dtr1.1/imageName:v1.0 
        serviceAccountName: serviceAccount1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   label:
      app.kubernetes.io/name: serviceAccount1
   name: serviceAccount1
rules:
  -apiGroups:
      - **
      -extensions
   resources:
      -configMaps
      -endpoints
      -events
      -ingresses
      -ingresses/status
      -services
   verbs:
      -create
      -get
      -list
      -update
      -watch
      -patch
  -apiGroups:
      - **
      -extensions
   resources:
      -nodes
      -pods
      -secret
      -namespace
      -services
   verbs:
      -get
      -list
      -watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   label:
      app.kubernetes.io/name: serviceAccount1
   name: serviceAccount1
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: serviceAccount1
subjects:
   -kind: ServiceAccount
    name: serviceAccount1
    namespace: 20048-game   
     
---
apiVersion: v1
kind: ServiceAccount
metadata:
   labels:
      app.kubernetes.io/name: serviceAccount1
   name: serviceAccount1
   namespace: 2048-game
